{
 "title": "Environmental",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "PM2.5 (Latest)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "airquality",
     "select": [
      [
       { "params": [ "pm25_standard" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PM10.0 (Latest)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "airquality",
     "select": [
      [
       { "params": [ "pm100_standard" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO2 (Latest)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CO2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "co2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Air Quality Concentrations Units",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "alias": "PM 1.0 ($tag_location)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "airquality",
     "select": [
      [
       { "params": [ "pm10_standard" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PM 2.5 ($tag_location)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "airquality",
     "select": [
      [
       { "params": [ "pm25_standard" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PM 10.0 ($tag_location)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "airquality",
     "select": [
      [
       { "params": [ "pm100_standard" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "alias": "CO2 ($tag_location)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "co2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of particles by size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 21 },
   "targets": [
    {
     "alias": "0.3um ($tag_location)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "airquality",
     "select": [
      [
       { "params": [ "particles_03um" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "0.5um ($tag_location)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "airquality",
     "select": [
      [
       { "params": [ "particles_05um" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "10um ($tag_location)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "airquality",
     "select": [
      [
       { "params": [ "particles_10um" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "25um ($tag_location)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "airquality",
     "select": [
      [
       { "params": [ "particles_25um" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "50um ($tag_location)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "airquality",
     "select": [
      [
       { "params": [ "particles_50um" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "100um ($tag_location)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "airquality",
     "select": [
      [
       { "params": [ "particles_100um" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 30 },
   "targets": [
    {
     "alias": "free ($tag_location)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "sysinfo",
     "select": [
      [
       { "params": [ "mem_free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "used ($tag_location)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "sysinfo",
     "select": [
      [
       { "params": [ "mem_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}